services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: frontend
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
